[package]
name = "magnet"
description = "Magnet link parsing and construction"
keywords = ["magnet", "bittorrent"]
readme = "README.md"

authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true

repository.workspace = true
version.workspace = true

[dependencies]
util = { path = "../util" }
url = "2"
base32 = "0.4"
