[package]
description = "Magnet link parsing and construction"
keywords = ["bittorrent", "magnet"]
name = "magnet"
readme = "README.md"

authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true

repository.workspace = true
version.workspace = true

[dependencies]
util = { path = "../util" }

base32 = "0"
url = "2"

