[package]
description = "Implementation of the bittorrent Local Peer/Service Discovery mechanism"
keywords = ["discovery", "local", "peer", "service"]
name = "lpd"
readme = "README.md"

authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true

repository.workspace = true
version.workspace = true
