[package]
description = "Efficient decoding and encoding for bencode."
keywords = ["bencode"]
name = "bencode"
readme = "README.md"

authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true

repository.workspace = true
version.workspace = true

[dependencies]
error-chain = "0.12"

[dev-dependencies]
criterion = "0.5"

[[bench]]
harness = false
name = "bencode_benchmark"
