[package]
name = "bencode"
description = "Efficient decoding and encoding for bencode."
keywords = ["bencode"]

authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
error-chain = "0.11"

[dev-dependencies]
criterion = "0.5"

[[test]]
name = "test"
path = "test/mod.rs"

[[bench]]
name = "bencode_benchmark"
harness = false