[package]
description = "uTorrent Transport Protocol"
keywords = ["bittorrent", "transport", "utp"]
name = "utp"
readme = "README.md"

authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true

repository.workspace = true
version.workspace = true
