[package]
description = "Communication with bittorrent HTTP trackers"
keywords = ["bittorrent", "http", "tracker"]
name = "htracker"
readme = "README.md"

authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true

repository.workspace = true
version.workspace = true
