[package]
description = "Bittorrent Infrastructure Project Piece Selection Module"
keywords = ["piece", "selection"]
name = "select"
readme = "README.md"

authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true

repository.workspace = true
version.workspace = true

[dependencies]
handshake = { path = "../handshake" }
metainfo = { path = "../metainfo" }
peer = { path = "../peer" }
util = { path = "../util" }
utracker = { path = "../utracker" }

bit-set = "0.5"
bytes = "0.4"
error-chain = "0.12"
futures = "0.1"
log = "0.4"
rand = "0.8"

[dev-dependencies]
futures-test = { git = "https://github.com/carllerche/better-future.git" }
